compiler: gcc
language: cpp
dist: bionic

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - p7zip-full

before_install:
  - cmake --version
  - cd $HOME
  - curl -LJO https://github.com/g-truc/glm/releases/download/0.9.9.8/glm-0.9.9.8.zip
  - 7z x glm-0.9.9.8.zip
  - dir
  - git clone https://github.com/Silverlan/sharedutils.git
  - cd sharedutils
  - git checkout 8148bf45cd95050b9bd39ff431daef85c2b29b2c
  - mkdir build
  - cd build
  - cmake .. -DDEPENDENCY_GLM_INCLUDE=${HOME}/glm -DSHAREDUTILS_STATIC=ON -DDEPENDENCY_MATHUTIL_INCLUDE=${TRAVIS_BUILD_DIR}/include/
  - make